"""Catalogue d'exemple, hors execution."""
from __future__ import annotations

from .models import ToolProfile

DEFAULT_TOOLS: tuple[ToolProfile, ...] = (
    ToolProfile(
        id="filesystem_read",
        name="Filesystem Read",
        description="Lit des fichiers locaux / read local files from the workspace.",
        server="filesystem",
        tags=("files", "read", "local", "fichier", "lire", "workspace"),
        tokens=80,
        permissions=("read_files",),
        fallback_id="docs_search",
        max_calls=20,
        scope="demo",
    ),
    ToolProfile(
        id="filesystem_write",
        name="Filesystem Write",
        description="Ecrit des fichiers locaux / write or edit local files.",
        server="filesystem",
        tags=("files", "write", "edit", "editer", "ecrire"),
        tokens=80,
        permissions=("read_files", "write_files"),
        fallback_id="filesystem_read",
        max_calls=10,
        scope="demo",
    ),
    ToolProfile(
        id="github_search",
        name="GitHub Search",
        description="Cherche des issues GitHub / search GitHub repositories and issues.",
        server="github",
        tags=("github", "search", "issues", "chercher", "code", "depot"),
        tokens=120,
        permissions=("read_github",),
        fallback_id="docs_search",
        max_calls=8,
        scope="demo",
    ),
    ToolProfile(
        id="browser",
        name="Browser",
        description="Navigue des pages web / browse web pages and extract content.",
        server="browser",
        tags=("web", "browser", "http", "page", "naviguer"),
        tokens=150,
        permissions=("browse_web",),
        fallback_id="docs_search",
        max_calls=6,
        scope="demo",
    ),
    ToolProfile(
        id="docs_search",
        name="Docs Search",
        description="Cherche dans la documentation / search project documentation and API.",
        server="docs",
        tags=("docs", "search", "documentation", "reference", "api"),
        tokens=60,
        permissions=("read_docs",),
        max_calls=12,
        scope="demo",
    ),
    ToolProfile(
        id="memory_select",
        name="Memory Select",
        description="Selectionne des memoires sous budget / select relevant memories.",
        server="memory",
        tags=("memory", "select", "context", "memoires", "selectionner", "budget"),
        tokens=100,
        permissions=("read_memory",),
        fallback_id="docs_search",
        max_calls=4,
        scope="demo",
    ),
    ToolProfile(
        id="shell",
        name="Shell",
        description="Execute des commandes shell. Hautes permissions. / run shell commands.",
        server="shell",
        tags=("shell", "exec", "command", "terminal"),
        tokens=200,
        permissions=("read_files", "write_files", "exec_shell"),
        max_calls=4,
        scope="demo",
    ),
)
